#pragma once

namespace rw
{
	enum class VirtualKey : uint8_t
	{
		RW_VK_NONE					= 0x00,
		RW_VK_LBUTTON				= 0x01, // Left mouse button
		RW_VK_RBUTTON				= 0x02, // Right mouse button
		RW_VK_CANCEL				= 0x03, // Control-break processing
		RW_VK_MBUTTON				= 0x04, // Middle mouse button (three-button mouse)
		RW_VK_XBUTTON1				= 0x05, // X1 mouse button
		RW_VK_XBUTTON2				= 0x06, // X2 mouse button
		RW_VK_BACK					= 0x08, // BACKSPACE key
		RW_VK_TAB					= 0x09, // TAB key
		RW_VK_CLEAR					= 0x0C, // CLEAR key
		RW_VK_RETURN				= 0x0D, // ENTER key
		RW_VK_SHIFT					= 0x10, // SHIFT key
		RW_VK_CONTROL				= 0x11, // CTRL key
		RW_VK_MENU					= 0x12, // ALT key
		RW_VK_PAUSE					= 0x13, // PAUSE key
		RW_VK_CAPITAL				= 0x14, // CAPS LOCK key
		RW_VK_KANA					= 0x15, // IME Kana mode
		//RW_VK_HANGUEL				= 0x15, // IME Hanguel mode(maintained for compatibility; use VK_HANGUL)
		RW_VK_HANGUL				= 0x15, // IME Hangul mode
		RW_VK_JUNJA					= 0x17, // IME Junja mode
		RW_VK_FINAL					= 0x18, // IME final mode
		RW_VK_HANJA					= 0x19, // IME Hanja mode
		RW_VK_KANJI					= 0x19, // IME Kanji mode
		RW_VK_ESCAPE				= 0x1B, // ESC key
		RW_VK_CONVERT				= 0x1C, // IME convert
		RW_VK_NONCONVERT			= 0x1D, // IME nonconvert
		RW_VK_ACCEPT				= 0x1E, // IME accept
		RW_VK_MODECHANGE			= 0x1F, // IME mode change request
		RW_VK_SPACE					= 0x20, // SPACEBAR
		RW_VK_PRIOR					= 0x21, // PAGE UP key
		RW_VK_NEXT					= 0x22, // PAGE DOWN key
		RW_VK_END					= 0x23, // END key
		RW_VK_HOME					= 0x24, // HOME key
		RW_VK_LEFT					= 0x25, // LEFT ARROW key
		RW_VK_UP					= 0x26, // UP ARROW key
		RW_VK_RIGHT					= 0x27, // RIGHT ARROW key
		RW_VK_DOWN					= 0x28, // DOWN ARROW key
		RW_VK_SELECT				= 0x29, // SELECT key
		RW_VK_PRINT					= 0x2A, // PRINT key
		RW_VK_EXECUTE				= 0x2B, // EXECUTE key
		RW_VK_SNAPSHOT				= 0x2C, // PRINT SCREEN key
		RW_VK_INSERT				= 0x2D, // INS key
		RW_VK_DELETE				= 0x2E, // DEL key
		RW_VK_HELP					= 0x2F, // HELP key
		RW_VK_0						= 0x30, // 0 key
		RW_VK_1						= 0x31, // 1 key
		RW_VK_2						= 0x32, // 2 key
		RW_VK_3						= 0x33, // 3 key
		RW_VK_4						= 0x34, // 4 key
		RW_VK_5						= 0x35, // 5 key
		RW_VK_6						= 0x36, // 6 key
		RW_VK_7						= 0x37, // 7 key
		RW_VK_8						= 0x38, // 8 key
		RW_VK_9						= 0x39, // 9 key
		RW_VK_A						= 0x41, // A key
		RW_VK_B						= 0x42, // B key
		RW_VK_C						= 0x43, // C key
		RW_VK_D						= 0x44, // D key
		RW_VK_E						= 0x45, // E key
		RW_VK_F						= 0x46, // F key
		RW_VK_G						= 0x47, // G key
		RW_VK_H						= 0x48, // H key
		RW_VK_I						= 0x49, // I key
		RW_VK_J						= 0x4A, // J key
		RW_VK_K						= 0x4B, // K key
		RW_VK_L						= 0x4C, // L key
		RW_VK_M						= 0x4D, // M key
		RW_VK_N						= 0x4E, // N key
		RW_VK_O						= 0x4F, // O key
		RW_VK_P						= 0x50, // P key
		RW_VK_Q						= 0x51, // Q key
		RW_VK_R						= 0x52, // R key
		RW_VK_S						= 0x53, // S key
		RW_VK_T						= 0x54, // T key
		RW_VK_U						= 0x55, // U key
		RW_VK_V						= 0x56, // V key
		RW_VK_W						= 0x57, // W key
		RW_VK_X						= 0x58, // X key
		RW_VK_Y						= 0x59, // Y key
		RW_VK_Z						= 0x5A, // Z key
		RW_VK_LWIN					= 0x5B, // Left Windows key(Natural keyboard)
		RW_VK_RWIN					= 0x5C, // Right Windows key(Natural keyboard)
		RW_VK_APPS					= 0x5D, // Applications key(Natural keyboard)
		RW_VK_SLEEP					= 0x5F, // Computer Sleep key
		RW_VK_NUMPAD0				= 0x60, // Numeric keypad 0 key
		RW_VK_NUMPAD1				= 0x61, // Numeric keypad 1 key
		RW_VK_NUMPAD2				= 0x62, // Numeric keypad 2 key
		RW_VK_NUMPAD3				= 0x63, // Numeric keypad 3 key
		RW_VK_NUMPAD4				= 0x64, // Numeric keypad 4 key
		RW_VK_NUMPAD5				= 0x65, // Numeric keypad 5 key
		RW_VK_NUMPAD6				= 0x66, // Numeric keypad 6 key
		RW_VK_NUMPAD7				= 0x67, // Numeric keypad 7 key
		RW_VK_NUMPAD8				= 0x68, // Numeric keypad 8 key
		RW_VK_NUMPAD9				= 0x69, // Numeric keypad 9 key
		RW_VK_MULTIPLY				= 0x6A, // Multiply key
		RW_VK_ADD					= 0x6B, // Add key
		RW_VK_SEPARATOR				= 0x6C, // Separator key
		RW_VK_SUBTRACT				= 0x6D, // Subtract key
		RW_VK_DECIMAL				= 0x6E, // Decimal key
		RW_VK_DIVIDE				= 0x6F, // Divide key
		RW_VK_F1					= 0x70, // F1 key
		RW_VK_F2					= 0x71, // F2 key
		RW_VK_F3					= 0x72, // F3 key
		RW_VK_F4					= 0x73, // F4 key
		RW_VK_F5					= 0x74, // F5 key
		RW_VK_F6					= 0x75, // F6 key
		RW_VK_F7					= 0x76, // F7 key
		RW_VK_F8					= 0x77, // F8 key
		RW_VK_F9					= 0x78, // F9 key
		RW_VK_F10					= 0x79, // F10 key
		RW_VK_F11					= 0x7A, // F11 key
		RW_VK_F12					= 0x7B, // F12 key
		RW_VK_F13					= 0x7C, // F13 key
		RW_VK_F14					= 0x7D, // F14 key
		RW_VK_F15					= 0x7E, // F15 key
		RW_VK_F16					= 0x7F, // F16 key
		RW_VK_F17					= 0x80, // F17 key
		RW_VK_F18					= 0x81, // F18 key
		RW_VK_F19					= 0x82, // F19 key
		RW_VK_F20					= 0x83, // F20 key
		RW_VK_F21					= 0x84, // F21 key
		RW_VK_F22					= 0x85, // F22 key
		RW_VK_F23					= 0x86, // F23 key
		RW_VK_F24					= 0x87, // F24 key
		RW_VK_NUMLOCK				= 0x90, // NUM LOCK key
		RW_VK_SCROLL				= 0x91, // SCROLL LOCK key
		RW_VK_LSHIFT				= 0xA0, // Left SHIFT key
		RW_VK_RSHIFT				= 0xA1, // Right SHIFT key
		RW_VK_LCONTROL				= 0xA2, // Left CONTROL key
		RW_VK_RCONTROL				= 0xA3, // Right CONTROL key
		RW_VK_LMENU					= 0xA4, // Left MENU key
		RW_VK_RMENU					= 0xA5, // Right MENU key
		RW_VK_BROWSER_BACK			= 0xA6, // Browser Back key
		RW_VK_BROWSER_FORWARD		= 0xA7, // Browser Forward key
		RW_VK_BROWSER_REFRESH		= 0xA8,	// Browser Refresh key
		RW_VK_BROWSER_STOP			= 0xA9, // Browser Stop key
		RW_VK_BROWSER_SEARCH		= 0xAA, // Browser Search key
		RW_VK_BROWSER_FAVORITES		= 0xAB, // Browser Favorites key
		RW_VK_BROWSER_HOME			= 0xAC, // Browser Start and Home key
		RW_VK_VOLUME_MUTE			= 0xAD, // Volume Mute key
		RW_VK_VOLUME_DOWN			= 0xAE, // Volume Down key
		RW_VK_VOLUME_UP				= 0xAF, // Volume Up key
		RW_VK_MEDIA_NEXT_TRACK		= 0xB0, // Next Track key
		RW_VK_MEDIA_PREV_TRACK		= 0xB1, // Previous Track key
		RW_VK_MEDIA_STOP			= 0xB2, // Stop Media key
		RW_VK_MEDIA_PLAY_PAUSE		= 0xB3, // Play / Pause Media key
		RW_VK_LAUNCH_MAIL			= 0xB4,	// Start Mail key
		RW_VK_LAUNCH_MEDIA_SELECT	= 0xB5, // Select Media key
		RW_VK_LAUNCH_APP1			= 0xB6, // Start Application 1 key
		RW_VK_LAUNCH_APP2			= 0xB7, // Start Application 2 key
		RW_VK_OEM_1					= 0xBA, // Used for miscellaneous characters; it can vary by keyboard.For the US standard keyboard, the ';:' key
		RW_VK_OEM_PLUS				= 0xBB, // For any country / region, the '+' key
		RW_VK_OEM_COMMA				= 0xBC, // For any country / region, the ',' key
		RW_VK_OEM_MINUS				= 0xBD, // For any country / region, the '-' key
		RW_VK_OEM_PERIOD			= 0xBE, // For any country / region, the '.' key
		RW_VK_OEM_2					= 0xBF, // Used for miscellaneous characters; it can vary by keyboard.For the US standard keyboard, the '/?' key
		RW_VK_OEM_3					= 0xC0, // Used for miscellaneous characters; it can vary by keyboard.For the US standard keyboard, the '`~' key
		RW_VK_OEM_4					= 0xDB, // Used for miscellaneous characters; it can vary by keyboard.For the US standard keyboard, the '[{' key
		RW_VK_OEM_5					= 0xDC, // Used for miscellaneous characters; it can vary by keyboard.For the US standard keyboard, the '\|' key
		RW_VK_OEM_6					= 0xDD, // Used for miscellaneous characters; it can vary by keyboard.For the US standard keyboard, the ']}' key
		RW_VK_OEM_7					= 0xDE, // Used for miscellaneous characters; it can vary by keyboard.For the US standard keyboard, the 'single-quote/double-quote' key
		RW_VK_OEM_8					= 0xDF, // Used for miscellaneous characters; it can vary by keyboard.
		RW_VK_OEM_102				= 0xE2, // Either the angle bracket key or the backslash key on the RT 102 - key keyboard
		RW_VK_PROCESSKEY			= 0xE5, // IME PROCESS key
		RW_VK_PACKET				= 0xE7, // Used to pass Unicode characters as if they were keystrokes.The VK_PACKET key is the low word of a 32 - bit Virtual Key value used for non - keyboard input methods.For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP
		RW_VK_ATTN					= 0xF6, // Attn key
		RW_VK_CRSEL					= 0xF7, // CrSel key
		RW_VK_EXSEL					= 0xF8, // ExSel key
		RW_VK_EREOF					= 0xF9, // Erase EOF key
		RW_VK_PLAY					= 0xFA, // Play key
		RW_VK_ZOOM					= 0xFB, // Zoom key
		RW_VK_PA1					= 0xFD, // PA1 key
		RW_VK_OEM_CLEAR				= 0xFE, // Clear key
	};
}